name: ci

on:
    push:
        paths-ignore:
            - "charts/**"
        branches:
            - "main"

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Cache node packages
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: npm install
              run: npm ci

            - name: npm test
              run: npm run test:ci

            - name: npm run build
              run: npm run build:ci

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=sha,prefix=,format=long

            - name: Build and push the Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
    # update:
    #     name: Update Helm Manifests
    #     runs-on: ubuntu-latest
    #     needs: build

    #     steps:
    #         - name: Check out code
    #           uses: actions/checkout@v4

    #         - name: Update Image Tag Values
    #           run: |
    #               chart_dir="charts"
    #               new_image_tag=${{ github.sha }}

    #               # Update the values.yaml file with the new image tag
    #               sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

    #         - name: Commit the changes made
    #           run: |
    #               git config --global user.name 'TechGardenCode'
    #               git config --global user.email 'techgardencode@gmail.com'
    #               git commit -am "feat: update image tag"
    #               git push
